name: "Upload to Dropbox"
description: "Upload files to Dropbox"
author: "Deka"
branding:
  icon: upload-cloud
  color: blue
inputs:
  dropbox_access_token:
    required: true
    description: "Dropbox access token"
  src:
    required: true
    description: "File to upload to Dropbox. e.g. 'file.txt', '**/*.txt'"
  dest:
    required: false
    default: "/"
    description: "Destination path for upload. e.g. '/file.txt', '/dest/'"
runs:
  using: "node12"
  main: "dist/index.js"
