name: 'build-test'
on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a file
        run: |
          echo "Hello" > file.txt
      - name: Upload a file
        id: upload
        uses: ./
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: file.txt
          dest: /test/my-file.txt
      - name: output
        run: |
          echo "${{steps.upload.outputs.shared_link}}"
      - name: Update file
        run: |
          echo "Hello updated" > file.txt
      - name: Overwrite file on Dropbox
        uses: ./
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: file.txt
          dest: /test/my-file.txt
          mode: overwrite
